name: Build & upload toolchain
on:
  push:
    branches:
      - master
  schedule:
    # 3 PM PST on Saturdays
    - cron: '0 22 * * SAT'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Install dependencies
      run: bash ci.sh deps
    - name: Build LLVM
      run: bash ci.sh llvm
    - name: Build binutils
      run: bash ci.sh binutils
    - name: Build kernel
      run: bash ci.sh kernel
